name: Release Build

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - name: Set version
        id: version
        run: echo "value=$(date -d '8 hour' -u +3.%y.%m%d%H)" >> "$GITHUB_OUTPUT"

      - name: Set up JDK 17
        uses: actions/setup-java@v5
        with:
          distribution: 'temurin'
          java-version: 17

      - name: Release Apk Sign
        run: |
          echo "RELEASE_KEY_ALIAS='${{ secrets.RELEASE_KEY_ALIAS }}'" >> gradle.properties
          echo "RELEASE_KEY_PASSWORD='${{ secrets.RELEASE_KEY_PASSWORD }}'" >> gradle.properties
          echo "RELEASE_STORE_PASSWORD='${{ secrets.RELEASE_STORE_PASSWORD }}'" >> gradle.properties
          echo "RELEASE_STORE_FILE='./key.jks'" >> gradle.properties
          echo "${{ secrets.RELEASE_KEY_STORE }}" | base64 --decode > app/key.jks

      - name: Unify version name
        run: |
          sed -i "/^def version/c def version = \"${{ steps.version.outputs.value }}\"" app/build.gradle

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v5

      - name: Build
        run: |
          chmod +x gradlew
          ./gradlew assembleAppRelease --build-cache --warning-mode all

      - name: Organize the Files
        run: |
          mkdir -p apk
          cp -f app/build/outputs/apk/app/release/*.apk apk/

      - name: Upload App To Artifact
        uses: actions/upload-artifact@v7
        with:
          name: legado_app
          path: apk/*.apk

      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          name: legado_app_${{ steps.version.outputs.value }}
          tag_name: ${{ steps.version.outputs.value }}
          body_path: CHANGELOG.md
          draft: false
          prerelease: false
          files: apk/*.apk
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
